site_name: My Docs
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
nav:
  - Home: index.md
  - Examples:
    - Basics: examples/basic.md
    - Lists: examples/lists.md
    - Dataclasses: examples/dataclasses.md
