site_name: "Documentation for Thermite - a CLI Generator"
theme:
  name: material
  features:
    - navigation.expand
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: "source"
            show_if_no_docstring: True
            separate_signature: true
            merge_init_into_class: true
            filters:
            - "!^_"
            - "!^__"
            show_root_toc_entry: False

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 2

nav:
  - Home: index.md
  - Customization:
    - CLI callbacks: ./cli_callbacks.md
    - Classes/Events: ./classes_events.md
  - Examples:
    - Basics: examples/basic.md
    - Lists: examples/lists.md
    - Dataclasses: examples/dataclasses.md
    - Advanced: examples/advanced.md
  - References: ./references.md
extra_css:
  - css/mkdocstrings.css
